 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: example-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: researchportal.info
     http:
       paths:
       - path: /api/sboot/(.*)
         backend:
           serviceName: sboot-service
           servicePort: 8080
       - path: /api/(feed)
         backend:
          serviceName: feed-service
          servicePort: 3002
       - path: /api/(interests)
         backend:
          serviceName: interest-service
          servicePort: 3001
       - path: /(.*)
         backend:
           serviceName: resweb-service
           servicePort: 80
