 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: example-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:3001;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
 spec:
   rules:
   - host: researchportal.info
     http:
       paths:
       - path: /api/(feed)
         backend:
          serviceName: feed-service
          servicePort: 3002
       - path: /api/(interests)
         backend:
          serviceName: interest-service
          servicePort: 3001
       - path: /(.*)
         backend:
           serviceName: resweb-service
           servicePort: 80
#Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress