apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-by-resource-utilization
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interestserver
  minReplicas: 1
  maxReplicas: 5
  metrics: 
  - type: Resource 
    resource: 
      name: memory
      target:
          type: AverageValue
          averageValue: 100M
  - type: Resource 
    resource: 
      name: cpu
      target:
          type: AverageValue
          averageValue: 5
